### ISSUE TITLE
first of a number of top-level layers never shows

### ISSUE THREAD

**Issue by nighliber** [softwhere/AddLayer-Widget#1]
Given a mapservice consisting of a number of "root" level layers, the first layer never displays regardless of visibility (adding as dynamic). Can enable by unchecking and checking in layer list.

mapservice
- layer - never shows
- layer - ok
- layer - ok

mapservice
- layer
  
  -sublayer - ok
  
  -sublayer - ok
- layer
  
  -sublayer - ok (etc)

**Comment by nighliber** [comment]
I've been told grouping is the term I'm looking for, in other words when adding a dynamic layer it will lose the first one if it is a collection of ungrouped layers.

For reference, visiblelayers doesn't ever seem to get the first layer regardless of layer config and AddLayer config. Additionally, the hidelayers set is "1,2,3,..." when visibility is on for the first layer, and ",1,2,3,..." when visibility is off so it looks like the first index is just getting dropped somewhere.

**Comment by softwhere** [comment]
Thanks for letting me know, nighliber. 
It sounds like an issue with the widget configuration code.
As a work-around, you can manually edit the config.json file to add the "0" index to the visibleLayers or hideLayers.

**Comment by nighliber** [comment]
I'll give it a shot, thanks! Long term though we'll need it to be automatic. I haven't poked around much yet, maybe I can patch it; if so I'll make a pull request.

**Comment by softwhere** [comment]
The problem was that the layerId is an integer but when passed to SimpleTable it is treated as text. 
SimpleTable included code like
 `textDiv.innerHTML = fieldData || "";`
when fieldData = 0 (as with the first layer), it converted it to an empty string.

The fix was to convert the layerId to a string before displaying in SimpleTable.

Thanks for catching this.

**Comment by nighliber** [comment]
Nice, thanks!
