### ISSUE TITLE
Widget failed to load - couldn't find icon

### ISSUE THREAD

**Issue by schlot** [softwhere/AddLayer-Widget#2]
I was not able to load this widget until I modified the name parameter in the widget's manifest.json file.  The original name was "Add Layer to Map".  Apparently that defined the path for where to find the AddLayer icon.  I got an error in the console: 
https://machinename:3344/webappbuilder/stemapp//widgets/Add%20Layer%20to%20Map/images/icon.png  404 not found.

Once I modified the name to "AddLayer", then the widget loaded and I was able to configure it.

**Comment by softwhere** [comment]
You're exactly right. I fixed the manifest.json file.
Thanks for catching this.
